"""add log_entry indexes

Revision ID: 0cff0988e210
Revises: 63b3a05696f0
Create Date: 2025-11-14 16:31:44.712000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cff0988e210'
down_revision: Union[str, Sequence[str], None] = '63b3a05696f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_log_entry_content'), 'log_entry', ['content'], unique=False)
    op.create_index(op.f('ix_log_entry_created_at'), 'log_entry', ['created_at'], unique=False)
    op.create_index(op.f('ix_log_entry_timestamp'), 'log_entry', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_entry_timestamp'), table_name='log_entry')
    op.drop_index(op.f('ix_log_entry_created_at'), table_name='log_entry')
    op.drop_index(op.f('ix_log_entry_content'), table_name='log_entry')
    # ### end Alembic commands ###
