#!/usr/bin/env python3
import datetime
from eternalog.data import connection, core as data_core

SAMPLE_CONTENT = ["Alpha", "Beta", "Gamma"]

def main() -> None:
    with connection.get_db_session() as db:
        for c in SAMPLE_CONTENT:
            data_core.log_entry_create(db, content=c, timestamp=datetime.datetime.now())
    print("Seeded sample log entries")

if __name__ == "__main__":
    main()
